# MiMo ASR 配置文件

# MiMo API Key（必填）
api_key = "你的APIKey"

# MiMo API 地址:
#OpenAI API:
base_url = "https://api.xiaomimimo.com/v1"
#Anthropic API:
#base_url = "https://api.xiaomimimo.com/v1"

#Token Plan-URL:
#OpenAI API:
#base_url = "https://token-plan-cn.xiaomimimo.com/v1"
#Anthropic API:
#base_url = "https://token-plan-cn.xiaomimimo.com/anthropic"
